### ISSUE TITLE
Links to https://atom.io/docs/api/latest/Config are broken

### ISSUE THREAD

**Issue by craaaa** [atom/flight-manual.atom.io#454] opened 2018-03-21 15:33 UTC
`scoped-settings-scopes-and-scope-descriptors.md` and `configuration-api.md` contain links to [https://atom.io/docs/api/latest/Config](https://atom.io/docs/api/latest/Config). This file existed in [v.1.24.1](https://atom.io/docs/api/v1.24.1/Config) but does not exist in v1.25.0, and is causing the Travis build to fail.

Links (and if applicable, content) should be updated as appropriate.

**Comment by Arcanemagus** [comment] 2018-03-21 19:25
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16955 which has already been fixed in https://github.com/atom/atom/pull/16957.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-21 19:25 UTC
