### ISSUE TITLE
404 - Broken link to chapter 3 from Atom Packages page

### ISSUE THREAD

**Issue by thisisnian** [atom/flight-manual.atom.io#120] opened 2015-08-29 02:02 UTC
Was browsing around and noticed that the following link was 404ing. Looks like the address was changed however the link was never updated.

The link is from Flight Manual -> 2: Using Atom -> Atom Packages (highlighted below)

![image](https://cloud.githubusercontent.com/assets/3102540/9519774/07150082-4d05-11e5-9cd2-875ff10fb492.png)

Moved from https://github.com/atom/atom.io/issues/28

**Comment by voltagex** [comment] 2015-10-12 05:43
Hey @thisisnian! Looks like the issue is in https://github.com/atom/docs/blob/master/book/01-introduction/sections/03-basics.asc#settings-and-preferences but I don't understand how ASCIIDoc's links work yet.

**Comment by gjtorikian** [comment] 2016-03-24 19:11
As we've moved off of Atlas in https://github.com/atom/flight-manual.atom.io/pull/158, this should be fixed.

**Closed by gjtorikian** 2016-03-24 19:11 UTC
Labels: address-with-nanoc, bug
